### ISSUE TITLE
Exception on unoptimized reified Tuple

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-model#14]
The example in https://github.com/ceylon/ceylon-sdk/issues/441 fails with the stack trace below.

```
ceylon run: possible undecidability: typechecker detected possible nontermination and aborted algorithm
com.redhat.ceylon.model.typechecker.model.DecidabilityException: possible undecidability: typechecker detected possible nontermination and aborted algorithm
    at com.redhat.ceylon.model.typechecker.model.Type.checkDepth(Type.java:1653)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:178)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:452)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:208)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyTuple(Type.java:462)
    at com.redhat.ceylon.model.typechecker.model.Type.isExactlyInternal(Type.java:337)
    at com.redhat.ceylon.model.typechecker.model.Type.isTypeArgumentListAssignable(Type.java:789)
    at com.redhat.ceylon.model.typechecker.model.Type.isSubtypeOfInternal(Type.java:697)
    at com.redhat.ceylon.model.typechecker.model.Type.isSubtypeOfInternal(Type.java:691)
    at com.redhat.ceylon.model.typechecker.model.Type.isSubtypeOf(Type.java:549)
    at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.is(TypeDescriptor.java:1361)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.isReified(Metamodel.java:346)
    at com.redhat.ceylon.compiler.java.Util.isReified(Util.java:63)
    at ceylon.promise.Deferred$promise_.foobar$priv$(Deferred.ceylon:159)
    at ceylon.promise.Deferred$promise_.map$canonical$(Deferred.ceylon:92)
    at ceylon.promise.Deferred$promise_.map(Deferred.ceylon:52)
    at ceylon.promise.Conjunction.map$canonical$(Conjunction.ceylon:58)
    at ceylon.promise.Conjunction.map(Conjunction.ceylon:57)
    at ceylon.promise.Completion$impl.completed$canonical$(Completion.ceylon:29)
    at ceylon.promise.Completion$impl.completed(Completion.ceylon:28)
    at ceylon.promise.Conjunction.completed$canonical$(Conjunction.ceylon)
    at ceylon.promise.Conjunction.completed(Conjunction.ceylon)
    at simple.run_.run(run.ceylon:13)
    at simple.run_.main(run.ceylon)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at ceylon.modules.api.runtime.SecurityActions.invokeRunInternal(SecurityActions.java:57)
    at ceylon.modules.api.runtime.SecurityActions.invokeRun(SecurityActions.java:48)
    at ceylon.modules.api.runtime.AbstractRuntime.invokeRun(AbstractRuntime.java:75)
    at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:122)
    at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:106)
    at ceylon.modules.Main.execute(Main.java:69)
    at ceylon.modules.Main.main(Main.java:42)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.jboss.modules.Module.run(Module.java:312)
    at org.jboss.modules.Main.main(Main.java:460)
    at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:244)
    at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:491)
    at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:380)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
    at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:41)
    at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:34)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.redhat.ceylon.launcher.Bootstrap.run(Bootstrap.java:55)
    at com.redhat.ceylon.launcher.Bootstrap.main(Bootstrap.java:32)
```

**Comment by gavinking** [comment]
Oh gawd, OK, this is nuts. It looks like we have some huge chain of linked `Tuple`s where each `Rest` is a union type. The union breaks the loop in `isExactlyTuple()` and forces us to revert to recursion.

I don't see any particular way to fix this in full generality, though perhaps it would be possible to fix certain special cases.

**Comment by gavinking** [comment]
Moving to 1.3.

**Comment by gavinking** [comment]
OIC, in #441 it's actually even more special than that because it's a chain of `Conjunction`s, not just plain `Tuple`s. i.s. @vietj has basically written his own flavor of `Tuple`.
