### ISSUE TITLE
problem with assert and Proxy 

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-model#20]
Given:

``` ceylon
import ceylon.interop.java {
    javaClassFromDeclaration
}
import ceylon.language.meta.model {
    Interface,
    Type
}

import java.lang {
    ObjectArray,
    JClass=Class
}
import java.lang.reflect {
    Proxy,
    InvocationHandler,
    JMethod=Method
}
import java.util.\ifunction {
    Predicate
}

shared void run() {
    Predicate<String> p = wrap(`Predicate<String>`, (String s) => s.empty);
    print("``p.test("")``, ``p.test("asdasd")``");
}

T wrap<T,out R,in A>(Type<T> t, R(A) fun) {
    assert (is Interface<T> i = `T`);
    value c = javaClassFromDeclaration(i.declaration);
    value a = ObjectArray<JClass<out Object>>(1);
    a.set(0, c);
    object handler satisfies InvocationHandler {
        shared actual Object? invoke(Object o, JMethod m, ObjectArray<Object> as) {
            assert (as.size==1, is A a = as.get(0));
            return fun(a) of Object?;
        }
    }
    assert (is T p = Proxy.newProxyInstance(c.classLoader, a, handler));
    return p;
}
```

I get:

```
ceylon run: Failed to resolve com.sun.proxy.$Proxy54
com.redhat.ceylon.model.loader.ModelResolutionException: Failed to resolve com.sun.proxy.$Proxy54
    at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:1643)
    at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:1602)
    at com.redhat.ceylon.model.loader.AbstractModelLoader.getDeclaration(AbstractModelLoader.java:4886)
    at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toProducedType(TypeDescriptor.java:309)
    at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toType(TypeDescriptor.java:301)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getProducedType(Metamodel.java:378)
    at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.is(TypeDescriptor.java:1361)
    at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.is(TypeDescriptor.java:263)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.isReified(Metamodel.java:344)
    at com.redhat.ceylon.compiler.java.Util.isReified(Util.java:63)
    at foo.wrap_.wrap(run.ceylon:38)
```

**Comment by jvasileff** [comment]
This is _possibly_ related to https://github.com/ceylon/ceylon.language/pull/626 where sub-typing was affected by `module` metadata, although the simpler examples in the PR now work (where the proxied type is non-generic).

But a further issue is that the `assert (is T ...)` should throw anyway, since we agreed that `is` tests on non-reified types should fail, like:

``` ceylon
value any = JArrayList<String>() of Anything;
assert (is JArrayList<String> any);
// Exception in thread "main" com.redhat.ceylon.compiler.java.language.ReifiedTypeError:
// Cannot determine whether class java.util.ArrayList is a java.util.ArrayList<ceylon.language.String>
```

**Comment by jvasileff** [comment]
BTW, in case you're interested, here is the public API for what I pretty much had working for Ceylon proxies:
- https://github.com/jvasileff/csm-petstore/blob/master/source-ih/com/vasileff/proxy/InvocationHandler.ceylon
- https://github.com/jvasileff/csm-petstore/blob/master/source/com/vasileff/csmpetstore/domain/support/createProxyInstance.ceylon
